pagopa/pagopa-ecommerce-payment-requests-service

helm/.helmignore
helm/Chart.yaml
helm/values-dev.yaml
helm/values-uat.yaml

Add helm dir and files for pipelines

Add helm files

---

tests/api-tests/payment-requests.api.tests.json

Add missing header deployment=blue for test request so that requests are redirect to blue instance
Fix necessary in order to perform api test call to the blue instance
Tested running deploy pipeline and check that requests are redirect to the blue instance

[CHK-711] add uat test

---

api-spec/payment-requests-api.yaml

Add missing 422 error code for carts post method
Align openapi specifications

fix: add missing 422 error code to carts post

---

.env.example
.gitignore
README.md
docker-compose.yml
pom.xml
src/main/kotlin/it/pagopa/ecommerce/payment/requests/domain/RptId.kt
src/main/kotlin/it/pagopa/ecommerce/payment/requests/repositories/CartInfo.kt
src/main/kotlin/it/pagopa/ecommerce/payment/requests/repositories/CartInfoRepository.kt
src/main/kotlin/it/pagopa/ecommerce/payment/requests/repositories/PaymentInfo.kt
src/main/kotlin/it/pagopa/ecommerce/payment/requests/services/CartService.kt
src/main/resources/application.properties
src/test/kotlin/it/pagopa/ecommerce/payment/requests/controllers/CartsControllerTests.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/domain/RptIdTest.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/services/CartsServiceTests.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/utils/CartRequests.kt

* Persist cart data when creating a new cart
* Local unit tests
* Local manual integration test

[CHK-728] feat(cart): persist cart data when creating a new cart

---

api-spec/payment-requests-api.yaml
src/main/kotlin/it/pagopa/ecommerce/payment/requests/errorhandling/ApiError.kt
src/main/kotlin/it/pagopa/ecommerce/payment/requests/errorhandling/ExceptionHandler.kt
src/main/kotlin/it/pagopa/ecommerce/payment/requests/exceptions/CartNotFoundException.kt
src/main/kotlin/it/pagopa/ecommerce/payment/requests/services/CartService.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/controllers/CartsControllerTests.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/services/CartsServiceTests.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/utils/CartRequests.kt

* implement endpoint to get single cart data

[CHK-723] feat(cart): implement endpoint to get single cart data

---

api-spec/payment-requests-api.yaml
src/main/kotlin/it/pagopa/ecommerce/payment/requests/services/CartService.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/controllers/CartsControllerTests.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/services/CartsServiceTests.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/tests/utils/CartRequests.kt
tests/api-tests/payment-requests.api.tests.json

1. Aligned implementation to the fixed open-api specification.
CartRequest.returnurls -> CartRequest.returnUrls
2. Changed POST carts location url to {checkoutHost}/{fiscalCode}{noticeNumber} until front-end will manage carts with relative GET carts api call 
This modification is needed to align implementation to the correct open-api carts specification.
The location url is changed so that this version can be correctly deployed into UAT environment without break checkout front-end application (does not manage get carts call by the moment)
local unit test and integration test (local)

fix: open-api specification alignment

---

src/main/kotlin/it/pagopa/ecommerce/payment/requests/repositories/PaymentRequestInfo.kt
src/main/kotlin/it/pagopa/ecommerce/payment/requests/services/PaymentRequestsService.kt

Refactoring PaymentInfo.isNM3 cache bean to align with the transactions used one's
This modification is required in order to save payment info cache as ecommerce-transactions module expect it
local test

fix: change isNM3 redis cache field name

---

helm/values-uat.yaml
pom.xml

Performed tuning optimizations
1. Enable Netty as WebServer
2. Enable autoscaling policy based on CPU consumption
Locally

fix: tuning + enable Netty

---

Dockerfile
applicationinsights.json
helm/values-uat.yaml

- add Azure Agent Application Insight to collects metrics and log https://learn.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent

feat: Enable Azure Monitor Application Insights

---

helm/values-dev.yaml

Increase POD resources for DEV environment
Increase resources after application insight introduction for DEV environment
Test performed in DEV environment

fix: increased POD resources for DEV

---

tests/api-tests/payment-requests.api.tests.json

Fix blue/green deployment test request for multiple payment notices adding missing mandatory field company name and description
Fix test request for blue/green deployment
Locally importing postman collection and sending request manually

fix: blue/greed deployment tests for multiple payment notices

---

src/main/kotlin/it/pagopa/ecommerce/payment/requests/services/PaymentRequestsService.kt

fix: get paName

---

.devops/code-review-pipelines.yml

Added into code review pipeline new stage for execute the integration test with pagopa-ecommerce-local.
For execute the regression check with all ecommerce project we have integrated an integration test phase with the local ecommerce project into the code review pipeline.
Testing was done with pipeline runs.

CHK-870 added integration test into code review pipeline

---

.env.example
Dockerfile.nodo-mock
api-tests/Dockerfile
api-tests/carts-api-tests.json
api-tests/env/carts-api-tests-env-local.json
pom.xml
src/main/kotlin/it/pagopa/ecommerce/payment/requests/client/NodoPerPmClient.kt
src/main/kotlin/it/pagopa/ecommerce/payment/requests/services/CartService.kt
src/main/resources/application.properties
src/test/kotlin/it/pagopa/ecommerce/payment/requests/clients/NodoPerPmClientTests.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/services/CartsServiceTests.kt

- Add NodoPerPM autogenerated client
- Add checkPosition logic in POST carts method
- Add checkPosition before carts saving procedure

[CHK-856] feat: add checkPosition call in POST cards

---

Dockerfile.nodo-mock
helm/values-dev.yaml
helm/values-uat.yaml
src/main/kotlin/it/pagopa/ecommerce/payment/requests/configurations/nodo/NodoConfig.kt
src/main/kotlin/it/pagopa/ecommerce/payment/requests/services/PaymentRequestsService.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/configurations/nodo/NodoConfigTests.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/services/PaymentRequestsServiceTests.kt

1. Fixed nodo request build (same fix as done into transactions module, see pagopa/pagopa-ecommerce-transactions-service#101)
2. Add missing NODO_PER_PM_URI environment system variable
This fix is needed in order to avoid concurrent request modification side effect that happens since nodo base requests are declared as singleton class fields and request fields are overridden by concurrent request processing
Local test

Chk 894 fix nodo request build

---

.devops/code-review-pipelines.yml
Dockerfile.nodo-mock
helm/values-dev.yaml
pom.xml
src/main/kotlin/it/pagopa/ecommerce/payment/requests/services/CartService.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/clients/NodoPerPmClientTests.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/services/CartsServiceTests.kt

- `esito` instead `outcome` in `checkposition` response
- depend on https://github.com/pagopa/pagopa-infra/pull/597
- update unit tests

fix: esito instead outcome in checkposition response

---

helm/values-dev.yaml
helm/values-uat.yaml
src/main/kotlin/it/pagopa/ecommerce/payment/requests/services/CartService.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/services/CartsServiceTests.kt

- update checkout url for redirect `POST carts`
The goal of this PR is to update checkout url  redirect according to solution described in `CHK-1010`.
```
async function sendCartUat(){
let request = {
"emailNotice":"test@test.it",
"paymentNotices": [
{
"noticeNumber":"302000100002673045",
"fiscalCode":"77777777777",
"amount":150,
"companyName":"Ente Creditore",
"description":"Test checkout",
}
],
"returnUrls":{
"returnOkUrl":`https://www.comune.it/user/area-personale/payment/payment_ok`,
"returnCancelUrl":`https://www.comune.it/user/area-personale/payment/payment_cancelled`,
"returnErrorUrl":`https://www.comune.it/user/area-personale/payment/payment_error`,
}
}
const res = await fetch('https://api.uat.platform.pagopa.it/checkout/ec/v1/carts', {
method: 'POST',
headers: {
'Accept': …
```

Chk 1010 redirect

---

api-spec/payment-requests-api.yaml
src/main/kotlin/it/pagopa/ecommerce/payment/requests/services/PaymentRequestsService.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/tests/utils/PaymentRequests.kt

Depends on pagopa/pagopa-infra#797
- Open api review: add missing information such as contact, DR link etc
- Removed unused `paymentContextCode` parameter
Those modifications are needed in order to add all information to the open api specifications
Junit tests

Chk 1253 open api review

---

api-spec/payment-requests-api.yaml
src/main/kotlin/it/pagopa/ecommerce/payment/requests/services/PaymentRequestsService.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/tests/utils/PaymentRequests.kt

Add deprecated `PaymentRequestsGetResponse.paymentContextCode` field
This field is still used by Checkout UAT version so it has been added to support both DEV and UAT version of Checkout frontend
Local junit tests

Chk 1304 add payment context code

---

src/main/kotlin/it/pagopa/ecommerce/payment/requests/repositories/PaymentRequestInfo.kt
src/main/kotlin/it/pagopa/ecommerce/payment/requests/repositories/PaymentTransferInfo.kt
src/main/kotlin/it/pagopa/ecommerce/payment/requests/services/PaymentRequestsService.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/services/PaymentRequestsServiceTests.kt

Update Payment Request Info in payment request adding transfer list
Added PaymentTrasferList and add the list to the paymentReqeustInfo dto
Update test
Upgrade to activateV2

Chk 1353 update payment request info

---

api-spec/payment-requests-api.yaml
helm/Chart.yaml

Add `idCart` and `allCCP` fields to cart request
Add optional fields to cartRequest definition

[CHK-1349] add optional fields to cartRequest

---

.devops/code-review-pipelines.yml
api-tests/carts-api-tests.json
src/main/kotlin/it/pagopa/ecommerce/payment/requests/repositories/CartInfo.kt
src/main/kotlin/it/pagopa/ecommerce/payment/requests/services/CartService.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/services/CartsServiceTests.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/tests/utils/CartRequests.kt

Added save on redis to the carId of the ec to manage in recovery on the GET of the cart.
To allow the recovery of the EC cartId passed in input during POST has been saved on redis.
In this way the ecommerce client will be able to perform an activation by passing the idCart input.
the tests were carried out in local.

CHK-1396-save-cartId

---

helm/values-uat.yaml

feat: update redirect to dev carts from uat

---

.github/workflows/check_pr.yml

Add pipeline to check the pr size and label it
Add pipeline file
This is a good tool to check how complex is the pr and if it is too large for a single task

[CHK-1400] add check pr pipeline

---

helm/values-uat.yaml

Set max payment notices to 1 in UAT env
Set max payment notices to 1 in UAT env because Checkout f.e. does not handle multiple payment notices properly

fix: set max items to 1 for UAT env

---

helm/values-prod.yaml

feat(helm): CHK-1539 add value for prod

---

.devops/deploy-pipelines.yml

Added kubectl install for green and blu deployment into deploy pipeline

fix-kubectl-task-into-deploy-pipeline

---

.devops/code-review-pipelines.yml

Fix problem while execute integration test stage into code review pipeline. 
In particular has been updated the command **docker-compose** to **docker compose**

fix: stage integration test into code review pipeline

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

Lowered initial delay
After changing application-insight agent with ELK one's deploy times are lower and so initial delay can be lowered accordingly
DEV and UAT deploys.
Acutal deploy times:
2023-06-01 12:18:41.487  INFO 1 --- [           main] mercePaymentRequestsServiceApplicationKt : Started PagopaEcommercePaymentRequestsServiceApplicationKt in 27.093 seconds (JVM running for 35.573)

fix: lowered initial delay

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
pom.xml
src/main/kotlin/it/pagopa/ecommerce/payment/requests/warmup/ControllersWarmup.kt
src/main/resources/logback-spring.xml

- Enable ECS log formatting through logback ecs encoder implementation
- Disable APM agent log sending
Those modifications are needed in order to format logs into ECS json format
Run with ecommerce local
`{"@timestamp":"2023-06-21T08:03:27.486Z","log.level": "INFO","message":"Started PagopaEcommercePaymentRequestsServiceApplicationKt in 1.708 seconds (JVM running for 1.934)","ecs.version": "1.2.0","service.name":"pagopa-ecommerce-payment-requests-service","service.version":"0.4.7","event.dataset":"pagopa-ecommerce-payment-requests-service","process.thread.name":"main","log.logger":"it.pagopa.ecommerce.payment.requests.PagopaEcommercePaymentRequestsServiceApplicationKt"}`

fix: json log formatting

---

.devops/azure-templates/chart-current-version.yml
.devops/deploy-pipelines.yml
helm/values-prod.yaml
helm/values-uat.yaml

feat(CD): CHK-1540 Add pipeline for prod

---

helm/values-prod.yaml

feat: enable log sending for payment-request

---

.devops/deploy-pipelines.yml
.github/actions/check-pr-semver-labels/action.yml
.github/workflows/check_pr.yml
.github/workflows/deploy.yml
README.md

Add github action that check for the presence of well-formed tags that will be used to trigger semantic versioning parameters for deploy module once PR is merge on main branch.
Those tags are:
| Tag                | Semantic versioning scope | Meaning                                                           |
|--------------------|---------------------------|-------------------------------------------------------------------|
| patch              | Application version       | Patch-bump application version into pom.xml and Chart app version |
| minor              | Application version       | Minor-bump application version into pom.xml and Chart app version |
| major              | Application version       | Major-bump application version into pom.xml and Chart app version |
| …

feat(CD): add action to trigger deploy pipeline on push on main branch

---

.devops/deploy-pipelines.yml

Fix api test on green instance being skipped
Fix api test on green instance being skipped

fix(deploy-pipeline): api test UAT green

---

.devops/deploy-pipelines.yml

Fix api test condition
Fix api test condition

fix(deploy-pipeline): api test UAT green condition

---

src/main/kotlin/it/pagopa/ecommerce/payment/requests/services/CartService.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/controllers/CartsControllerTests.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/services/CartsServiceTests.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/tests/utils/CartRequests.kt

Mail in carts request is optional.
In case request does not contains mail the cart request processing is interrupted because mail is wrongly treat as not nullable.
The solution is to treat mail as optional, as for SANP and api specifications
Those modifications are needed in order to allow mail to be null
Junit tests + local tests with ecommerce local

[CHK-1722] - fix(optional-mail): make mail optional

---

src/main/kotlin/it/pagopa/ecommerce/payment/requests/services/PaymentRequestsService.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/services/PaymentRequestsServiceTests.kt

- Add tracing for both success and error nodo operations (see below screenshots)
- Add error code into span title in order to read fault code directly in transaction timeline section (see below screenshots)
This fix is needed in order to success nodo operations to be visible in Nodo monitoring dashboards
Junit + test in dev environment
OK verify payment notice: 
KO verify payment notice
Kibana dashboard:

fix(monitoring): trace all nodo operations

---

helm/values-uat.yaml

feat: update cart redirect

---

helm/values-prod.yaml

Enable Open telemetry log sending for PROD env
Enable Open telemetry log sending for PROD env

fix: enable otlp log exporter for prod env

---

.devops/code-review-pipelines.yml

Reduced duration of the code review pipeline.

fix(CR): fixed pipeline duration

---

.devops/code-review-pipelines.yml

Fixed collection folder position into ecommerce local used into CR pipeline

fix(CR pipeline): fixed path collection tests into ecommerce local

---

helm/values-dev.yaml

feat: CHK-1979 Enable uat nodo for dev ecommerce

---

.devops/deploy-pipelines.yml

Added stages for execute e2e tests after DEV and UAT deploy.
The change was made to perform tests on the FE after the deployment of the service.

feat(deploy pipeline): CHK-1999 e2e tests

---

helm/values-prod.yaml

- set minReplica to 3 for prod env, one for availability zone;
- add antiPodAffinity with[ topology.kubernetes.io/zone](https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesiozone);
The goal of this PR is to increase the availability  by deploying at least one pod per availability zone.

feat: CHK-2075 add antipodaffinity

---

src/main/kotlin/it/pagopa/ecommerce/payment/requests/configurations/redis/RedisConfiguration.kt

Fixed redis ttl for paymentRequestInfo collection from 1 minute to 15

fix(deploy pipeline): fixed redis ttl

---

helm/values-prod.yaml

feat: CHK-1987 disable log sending from apm agent (elk)

---

.devops/deploy-pipelines.yml
helm/values-dev.yaml

The goal of this PR is to keep a beta version in the DEV environment that calls the DEV node instead of the UAT node.

chore: add beta for testing nodo dev

---

api-spec/payment-requests-api.yaml
src/main/kotlin/it/pagopa/ecommerce/payment/requests/errorhandling/ExceptionHandler.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/controllers/PaymentRequestsControllerTests.kt

- update node error handler
- update openapi
The goal of this PR is to update node error handler according _new_ ( @MarcoTormen :-)  ) requirement, described in this [docs](https://pagopa.atlassian.net/wiki/spaces/I/pages/867565570/eCommerce+-+Errori+in+verifica+attivazione+e+autorizzazione).
please pay attention to openapi updates https://editor.swagger.io/?url=https://raw.githubusercontent.com/pagopa/pagopa-ecommerce-payment-requests-service/1ad41b712435e59ec3680495d3c7a2ad2707d942/api-spec/payment-requests-api.yaml

CHK-2694: update node error handler

---

src/main/kotlin/it/pagopa/ecommerce/payment/requests/configurations/webclients/WebClientsConfig.kt

Configure Netty DNS resolver to use 1 as number of dots in name resolution
This modification is a porting of the fix performed [here](https://github.com/pagopa/pagopa-ecommerce-payment-methods-service/pull/191) and applied to all clients
Test in UAT env (during performance tests)

fix: ndots

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
src/main/resources/application.properties

This PR adds a new deployment strategy by setting maxSurge to 1 and maxUnavailable to 0. Also setup spring boot's graceful shutdown.
- set maxSurge to 1 and maxUnavailable to 0. In this way running pods keeps active and only one new pod at time is started
- enabled spring boot graceful shutdown by setting it on application.properties file. Also extended the gracefull windows to 25 seconds
- explicitly set k8s graceful period to 30 seconds
Tested on dev with 3 replicas

feat: Add new deployment strategy

---

helm/values-prod.yaml

feat: enable carts with 5 payment notices

---

helm/values-prod.yaml

fix max carts payment notice

---

helm/values-prod.yaml

feat(update resources): set min replica to 5 in prod

feat(update resources): set min replica to 5 in prod

---

api-spec/payment-requests-api.yaml
helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
src/main/kotlin/it/pagopa/ecommerce/payment/requests/configurations/redis/RedisConfiguration.kt
src/main/kotlin/it/pagopa/ecommerce/payment/requests/controllers/CartsController.kt
src/main/kotlin/it/pagopa/ecommerce/payment/requests/repositories/PaymentRequestInfo.kt
src/main/kotlin/it/pagopa/ecommerce/payment/requests/services/CartService.kt
src/main/kotlin/it/pagopa/ecommerce/payment/requests/services/PaymentRequestsService.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/configurations/openTelemetry/OpenTelemetryConfigurationTests.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/controllers/CartsControllerTests.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/repositories/redistemplate/PaymentRequestsRedisTemplateWrapperTest.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/services/CartsServiceTests.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/services/PaymentRequestsServiceTests.kt

Depends on https://github.com/pagopa/pagopa-infra/pull/2360
Added x-client-id header to POST carts API request, updated openAPI specs accordingly
Added clientId query param to POST carts API response redirection url

[CHK-3116] feature(post-carts): add x-client-id header to POST carts 

---

.devops/azure-templates/chart-github-release.yml
.devops/code-review-pipelines.yml

- updated versions for pipeline tasks which generated deprecation warnings on remote build and deploy processes
This update was needed to prevent future execution failures on code review and deploy pipelines
- Pipeline jobs executed successfully and without deprecation warnings

[PIDM-41] chore(azdo-pipeline-tasks): update tasks versions

---

src/main/kotlin/it/pagopa/ecommerce/payment/requests/services/CartService.kt
src/test/kotlin/it/pagopa/ecommerce/payment/requests/services/CartsServiceTests.kt

- Handled case with duplicated paymentNotice request.
In case of requests with duplicated paymentNotice, the system must respond with an error and block the payment flow.
Unit test

[PIDM-219] fix(post-carts): handle duplicate payments notice

---

helm/values-prod.yaml
helm/values-uat.yaml

[CHK-4001] Helm fix of missing env vars

---

src/main/resources/META-INF/native-image/reflect-config.json

Some classes were missing from reflect-config.json file, leading to **kotlin.reflect.jvm.internal.KotlinReflectionInternalError: Unresolved class** errors

[CHK-4364] feat(graalvm): add problem json dto classes to reflect-config.json

---

.devops/code-review-pipelines.yml
.devops/deploy-pipelines.yml
.env.example
Dockerfile.jvm
Dockerfile.native
README.md
dep-sha256.json
pom.xml
settings.xml.template

- Injected GitHub Packages authentication logic across Dockerfiles and pipelines so builds can use a GitHub token when required (supports both CI and local/dev flows via Docker secrets).
- Updated Dockerfile(s) to support Docker secrets for token-based authentication and adjusted build steps to accept injected credentials.
- Added `settings.xml.template` file to provide a Maven settings template that is populated with GitHub token credentials when needed.
- Updated `.devops/code-review-pipelines.yml` to expose/use a `GITHUB_RO_TOKEN` pipeline variable where authentication is required.
- Updated integration test Docker builds to accept and use GitHub Packages authentication (when applicable).
- Rewrote docker build/push steps in `deploy-pipelines.yml` as an override of …

feat: [CHK-4408] adding pagopa depcheck plugin for dependencies verification
